name             'ocax'
maintainer       'J. Felix Ontanon'
maintainer_email 'felixonta@gmail.com'
license          'GNU Affero General Public License v3'
description      'Installs/Configures a OCAX app. More iformation at http://ocax.net'
version          '0.1'
depends          'database'
depends          'apache2'
depends          'mysql'
